### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mabomb** [maximilianallan/miccai-challenge-scripts#1]
Dear @maximilianallan ,
is the dataset publicly available?

**Comment by maximilianallan** [comment]
Yes, the 2017 data is here: https://endovissub2017-roboticinstrumentsegmentation.grand-challenge.org/Downloads/
Some similar data from 2018 is here: https://endovissub2018-roboticscenesegmentation.grand-challenge.org/Downloads/ 

Register for both challenges and you'll get the links
